apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding
  sessionAffinity: None
  type: LoadBalancer
